### ISSUE TITLE
reference to invalid character number

### ISSUE THREAD

**Issue by KarolKaczmarek** [matteocontrini/sms-wp-to-android#1]
Hi,
I tried running convert.py on my msg file and am getting:
```
PS C:\git\sms-wp-to-android> python .\convert.py
Traceback (most recent call last):
  File ".\convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 280, column 0
PS C:\git\sms-wp-to-android>
```

I found out that it may be due to parser restrictions: http://stackoverflow.com/questions/7693515/why-is-elementtree-raising-a-parseerror but was wondering whether you could provide some workaround wit existing on new parser?

**Comment by matteocontrini** [comment]
Can you check what you have in the file at line 280? Any special/wrong character perhaps?

**Comment by KarolKaczmarek** [comment]
Thanks after removing it it worked. Should have checked it earlier.

**Comment by KarolKaczmarek** [comment]
Rest of the process went smoothly, thanks a lot!

**Comment by matteocontrini** [comment]
Glad to hear that.
I've discovered there are troubles with some conversations when you use SMSes again on Android. In particular when someone sends you an SMS, another conversation for the same contact will be created, and I couldn't find a way to merge the 2 or make them match.

I'm used to Windows Phone where you can link contacts and conversations automatically... A reason why I shouldn't have switched away :P :P

**Comment by KarolKaczmarek** [comment]
Haven't noticed this. New texts appear in the old conversation threads for me (Android 5.1.1)
