### ISSUE TITLE
Picture Problem

### ISSUE THREAD

**Issue by billwilts** [matteocontrini/sms-wp-to-android#10]
The process you have designed works brilliantly apart from one issue! It seems that if there are any pictures in the messages the Python script skips the body content for all messages. Not bother about the pictures but I would like to get the message content. Any chance of a fix?

**Comment by matteocontrini** [comment]
What do you mean that it skips "the body for all messages"? Does it crash or something?

**Comment by billwilts** [comment]
Matteo,

No, actually I’m an idiot!

I was trying to restore the wrong file. Just used the right file and it works perfectly.

Sorry for the trouble. ☹

Regards,
Bill.
bill@thebelgroves.org<mailto:bill@thebelgroves.org>

**Comment by matteocontrini** [comment]
Np
