### ISSUE TITLE
convert.pl script returns with error

### ISSUE THREAD

**Issue by oladimj** [matteocontrini/sms-wp-to-android#12]
Got this error after running the convert.py script and on selecting the .msg file already copied into my computer folder. Please help.
Python 2.7 (r27:82525, Jul  4 2010, 07:43:08) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART ================================
>>> 

Traceback (most recent call last):
  File "C:\Users\oladimj\Documents\Nokia to Android Backup\sms-wp-to-android-master\convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1176, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 653, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1623, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1487, in _raiseerror
    raise err
ParseError: reference to invalid character number: line 821, column 2042
>>>

**Comment by matteocontrini** [comment]
Can you check at line 821, column 2042 if there's some strange character?
See also #7 and #11

**Comment by oladimj** [comment]
Please note I've got little or no experience with python anyway. I'm following your procedure on how to transfer my SMS messages from Nokia to Android

**Comment by oladimj** [comment]
I'm using the same convert.pl script you shared.

**Comment by oladimj** [comment]
Thanks Matte. I got it running it but quite slow; guess that's a function of the laptop device I'm using. Had to download Editplus to clean up all the unknown characters. 
Gracias!
