### ISSUE TITLE
Problem with converting

### ISSUE THREAD

**Issue by freemanvrn** [matteocontrini/sms-wp-to-android#14]
Hi! I have some problems while trying to use your script. Can you help me to find why it doesn’t work?

Traceback (most recent call last):
 File “C:\Users\freemanvrn\Desktop\convert\convert.py”, line 13, in <module>
 e = ET.parse(file_path).getroot()
 File “C:\Python27\lib\xml\etree\ElementTree.py”, line 1182, in parse
 tree.parse(source, parser)
 File “C:\Python27\lib\xml\etree\ElementTree.py”, line 656, in parse
 parser.feed(data)
 File “C:\Python27\lib\xml\etree\ElementTree.py”, line 1653, in feed
 self._raiseerror(v)
 File “C:\Python27\lib\xml\etree\ElementTree.py”, line 1517, in _raiseerror
 raise err
ParseError: reference to invalid character number: line 53, column 5242

Thanks!

**Comment by matteocontrini** [comment]
Please check similar issues #7 #11 #12
