### ISSUE TITLE
script failing - 'xml.etree.ElementTree.ParseError: syntax error: line 1, column 0' error

### ISSUE THREAD

**Issue by the-top-dollar** [matteocontrini/sms-wp-to-android#15]
Hi

Thanks for the work on developing this script.  Much appreciated!

My situation:
> Windows 10 phone
> Transfer My Data - 7500 messages - creates sms.vmsg file.  All as expected . . .
> But then applying the scipot to this.vsmg file gives the following dialog:

springle@springle-Latitude-E4200 ~/Downloads/sms-wp-to-android-master $ python2.7 convert.py
Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

Seems to be saying error at top of file - but column 0?  Surely first column is '1'?

Any ideas/suggestions on how to fix?

Best, SP

**Comment by matteocontrini** [comment]
Can you open the file and check what's in the first line?
Btw column indexes start with 0

**Comment by the-top-dollar** [comment]
Blimey - quick reponse!!!

First 30 or so lines of file set out below, extracted using gedit (text 
starts with BEGIN)

BEGIN:VMSG
VERSION: 1.1
BEGIN:VCARD
TEL:+447789981760
END:VCARD
BEGIN:VBODY
X-BOX:SENDBOX
X-READ:READ
X-SIMID:0
X-LOCKED:UNLOCKED
X-TYPE:SMS
Date:2016/07/22 14:03:43
Subject;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:Cheers
END:VBODY
END:VMSG
BEGIN:VMSG
VERSION: 1.1
BEGIN:VCARD
TEL:+447789981760
END:VCARD
BEGIN:VBODY
X-BOX:INBOX
X-READ:READ
X-SIMID:0
X-LOCKED:UNLOCKED
X-TYPE:SMS
Date:2016/07/22 13:46:28
Subject;ENCODING=QUOTED-PRINTABLE;CHARSET=UTF-8:Hi, Simon. It's 
Alan.Harding@neweconomymanchester.com
END:VBODY
END:VMSG

Best, Simon P

**Comment by matteocontrini** [comment]
That's a different format I've never seen.
What app did you use for exporting the messages?

**Comment by matteocontrini** [comment]
Ok, it seems that .vmsg is a standard format. You may be able to import them directly with some apps on the Play Store. Just search for "vmsg" on the Store.

**Comment by the-top-dollar** [comment]
Matteo - thanks for the help/pointers.  Will give VMG converter a try

SDP
