### ISSUE TITLE
Unicode Decode error

### ISSUE THREAD

**Issue by Ema85** [matteocontrini/sms-wp-to-android#17]
Hello there,

The following error occurs when i'm executing your script, any idea of what i'm doing wrong?
Thanks a lot!

Elodie

```
C:\Users\elodie\Desktop\Nouveau dossier>c:\python27\python.exe convert.py
Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1176, in parse
    tree.parse(source, parser)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 653, in parse
    parser.feed(data)
  File "c:\python27\lib\xml\etree\ElementTree.py", line 1621, in feed
    self._parser.Parse(data, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe5 in position 4: invalid continuation byte
```

**Comment by matteocontrini** [comment]
Try checking #7 #11 #12

**Comment by Ema85** [comment]
I've already read these posts but i wasn't sure where to look to find the issue : my error is just mentionning byte 0xe5 and position 4 but no line no colums.
Thank you for your time.

**Comment by matteocontrini** [comment]
Can you try this method?
http://stackoverflow.com/a/21470447/1633924

You should add those lines in the script file

**Comment by Ema85** [comment]
I tried it but still not working :-/
(By the way thanks for your very quick answer!)

**Comment by matteocontrini** [comment]
Are you able to check in the XML file (the .msg file) if there's something strange at position 4? Which I guess means column 4 (or 5 depending on whether the count is zero-based or not) in the first line

**Comment by Ema85** [comment]
I already looked at the xml file and i can not figure what's wrong, it is starting like this :  `<?xml version="1.0" encoding="utf-8"?>`
I also tried to type again the entire marker in case there is a hidden character.

Maybe you could send me a valid .msg file and i could check if something is different?

**Comment by matteocontrini** [comment]
Can you also try to re-save the file as an UTF-8 encoded file?
You should be able to do that in most editors doing something like "File => Save with encoding" or similar.

**Comment by Ema85** [comment]
Hello there. It wasn't working when re-saving as an UTF-8 encoded file. 
I borrowed a phone to get a valid .msg file and then i made a copy from my .msg file to the valid .msg file, now it's working perfectly. Thanks a lot for your help and your quick answer.
Your script saved my messages, thank you !
