### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by drojas7** [matteocontrini/sms-wp-to-android#2]
Hi there. 

I am trying to use your script with Python 2.7.10 on Mac OS X 10.11.1 and I'm getting the following error when selecting my .msg file:

Total count of messages: 16360

[===                 ] processing 2478Traceback (most recent call last):
  File "convert.py", line 34, in <module>
    body = m.find('Body').text.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

Any idea on how to fix this?

Thanks!

David

**Comment by matteocontrini** [comment]
There's probably something invalid in the .msg file. Can you try to print out [a string representation](http://stackoverflow.com/questions/15304229/how-can-i-convert-python-elementtree-to-string) of the `m` node so that you can take a look at what's wrong with that particular one when it fails? 

Thanks

**Comment by drojas7** [comment]
I'm not sure I understand what you mean... I'm a newbie when it comes to
python. Could you explain? Thanks!

**Comment by matteocontrini** [comment]
Is it a problem to send me the .msg file?
It's a bit difficult to fix the issue without a repro case...

**Comment by matteocontrini** [comment]
@drojas7 can you pull the latest commit and run the script again? It will still fail, but it will print out the XML node that's causing troubles. And if you can, post it here (or send me an email), removing sensitive information. A child node should be missing...

**Comment by BF-Medic** [comment]
@matteocontrini Hi. With the last commit I get this "error":
File "convert.py", line 5
 <!DOCTYPE html>
SyntaxError: invalid syntax

With last version i got the same error as @drojas7

**Comment by matteocontrini** [comment]
It seems you're using a wrong .msg file.
It's throwing an error because the parser finds an HTML doctype declaration, which is unexpected.

**Comment by BF-Medic** [comment]
Something went wrong there last time.  Now I get this:
Total count of messages: 9074

[=                   ] processing 506<?xml version='1.0' encoding='utf8'?>
<Message><Recepients /><Body /><IsIncoming>true</IsIncoming><IsRead>true</IsRead><Attachments />
<LocalTimestamp>130892297473104287</LocalTimestamp><Sender>Mobile operator</Sender></Message>
Traceback (most recent call last):
  File "convert.py", line 38, in <module>
    raise e
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by BF-Medic** [comment]
I got it to run now, but I get this:

Total count of messages: 9074

[=                   ] processing 506<?xml version='1.0' encoding='utf8'?>
<Message><Recepients /><Body /><IsIncoming>true</IsIncoming><IsRead>true</IsRead><Attachments />
<LocalTimestamp>130892297473104287</LocalTimestamp><Sender>Mobile operator</Sender></Message>
Traceback (most recent call last):
  File "convert.py", line 38, in <module>
    raise e
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by matteocontrini** [comment]
Can you try after 2e6b32e3015b690e2e656007882a73da9d864076 commit?

**Comment by BF-Medic** [comment]
Thanks for the quick help. It startet counting now then I got this:

Total count of messages: 9074

[=======             ] processing 3442Traceback (most recent call last):
  File "convert.py", line 66, in (module)
    body=body
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 3:
ordinal not in range(128)

**Comment by matteocontrini** [comment]
Try with cd2eab3fa0dfc06f104ce435903defbd95ca0735

**Comment by matteocontrini** [comment]
Try with cd2eab3fa0dfc06f104ce435903defbd95ca0735

**Comment by BF-Medic** [comment]
Total count of messages: 9074

[                    ] processing 1Traceback (most recent call last):
  File "convert.py", line 66, in [module]
    body=body
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal
not in range(128)

**Comment by matteocontrini** [comment]
I can't reproduce the issue so I'm doing attempts... try after 2654d90968b509811fba2f6bb2f4bf201a4cfb6b

**Comment by BF-Medic** [comment]
Gave me the same as previous:
Total count of messages: 9074

[=======             ] processing 3442Traceback (most recent call last):
  File "convert.py", line 66, in module
    body=body
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 3:
ordinal not in range(128)

**Comment by matteocontrini** [comment]
Can you search in the .msg file if that char `\xa0` is actually there? And if you find it, can you look if there's something particular in that message? If you can't identify anything, can you send me (even privately) some text of that text message?

Thank you for the patience

**Comment by BF-Medic** [comment]
I don't find \xa0 when searching the file with Notepad++

**Comment by BF-Medic** [comment]
After reading others having trouble with \xa0 in Python scripts, as it is an "hard-space" or something?
Should I try to translate it to a normal space or something maybe?

**Comment by matteocontrini** [comment]
You should if you can identify it.

**Comment by BF-Medic** [comment]
Success after last update! You rock.
