### ISSUE TITLE
error with command "convert.py"

### ISSUE THREAD

**Issue by washiall** [matteocontrini/sms-wp-to-android#21]
I followed your steps to convert my smses from windows to Android.  At this stage of convert command I keep getting errors and cannot proceed from the command "convert.py" 

Could you please send to me any additional commands or process steps I should use?

Thanks

**Comment by matteocontrini** [comment]
Hi, could you specify the errors you're getting?

**Comment by washiall** [comment]
Hi See below. Says 'convert' is not defined

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> convert.py

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    convert.py
NameError: name 'convert' is not defined
>>>

**Comment by washiall** [comment]
Hi,

I get the error that 'convert' is not defined

Hope I can get a fix.

Thanks,

Allan
--------------------------------------------
On Tue, 10/18/16, Matteo Contrini <notifications@github.com> wrote:

 Subject: Re: [matteocontrini/sms-wp-to-android] error with command "convert.py" (#21)
 To: "matteocontrini/sms-wp-to-android" <sms-wp-to-android@noreply.github.com>
 Cc: "washiall" <aomondiw@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Tuesday, October 18, 2016, 5:25 PM
 
 Hi, could you specify the errors
 you're getting?
 
 —
 You are receiving this because you authored the thread.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by matteocontrini** [comment]
You need to launch a cmd window and then run `python convert.py`

**Comment by washiall** [comment]
cmd from python or from dos promt?

I did the above from python and i get:

 syntax error: invalid syntax

**Comment by matteocontrini** [comment]
`cmd` **is** the command prompt. Click Start => write "cmd" or "command prompt"

**Comment by washiall** [comment]
so that's from dos prompt?

**Comment by washiall** [comment]
that results into:

'python' is not recognized as an internal or external command, operable program or batch file.

**Comment by matteocontrini** [comment]
You need to add Python to your PATH env variable

**Comment by washiall** [comment]
sorry I may not be following correctly. this is what i typed on the dos cmd prompt that resulted in the error:
C:\users\user>python convert.py

**Comment by washiall** [comment]
what am i missing, that command is not working.. ?

**Comment by washiall** [comment]
Hey, it has finally worked :-) than you so much. I realized there was a step I missed. Basically I was downloading and installing python but not the program itself. So once I downloaded the program it worked like magic !

**Comment by washiall** [comment]
i.e I wasn't downloading the code 'convert'

**Comment by washiall** [comment]
And one question now, WHAT ABOUT WHATSAPP MESSAGES, any way to convert?

**Comment by washiall** [comment]
I backed up already on onedrive
but cannot get them on the Android ...?
