### ISSUE TITLE
Cannot load sys??

### ISSUE THREAD

**Issue by ocalvo** [matteocontrini/sms-wp-to-android#25]
scar@Oscar-Surface:/mnt/c/dd/WPBackup/sms-wp-to-android-master/sms-wp-to-android-master$ python convert.py
Traceback (most recent call last):
  File "convert.py", line 4, in <module>
    if (sys.version_info > (3, 0)):
NameError: name 'sys' is not defined
oscar@Oscar-Surface:/mnt/c/dd/WPBackup/sms-wp-to-android-master/sms-wp-to-android-master$

**Comment by matteocontrini** [comment]
Try downloading/cloning the repo again and let me know
