### ISSUE TITLE
Error converting msg-file from Lumia 950

### ISSUE THREAD

**Issue by SagaPer** [matteocontrini/sms-wp-to-android#26]
I have backed up sms messages from my Microsoft Lumia 950 to file in phone, copied file to Win 10 pc with Python 2.7 installed. 

Opens CMD window in admin mode, change to Python folder (msg-file is also located in Pyhon folder), starts command python convert.py, picks msg-file and process script. Get this output:

C:\Python27>python convert.py
Total count of messages: 5325

[                    ] processing 1Traceback (most recent call last):
  File "convert.py", line 78, in <module>
    body=body
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 94: ordinal not in range(128)

What to do?

**Comment by matteocontrini** [comment]
Try checking #7 #11 #12

**Comment by SagaPer** [comment]
I have opened xml-file in both XML editor and crimson editor and I am unsure on where to look for source to error. Do u'\xe5 refer to a spesific letter or sign and in what line and position to look for problem?

**Comment by matteocontrini** [comment]
Can you try cloning/downloading the repository again and running the script? The issue might be caused by a recent code change.

**Comment by SagaPer** [comment]
Restarted pc, downloaded repository again, ran script, success! I will now try to import to Android phone. Thanx.
