### ISSUE TITLE
No output file

### ISSUE THREAD

**Issue by peter1017** [matteocontrini/sms-wp-to-android#28]
Hi - followed all your instructions but the .py file is not producing an output file. 

I managed to screenshot the DOS screen and could make out, something similar to

Type error: 'encoding' is an invalid keyword argument for this function.

Sorry, complete novice with such things!

**Comment by matteocontrini** [comment]
Make sure you have Python installed and that the script is being run with Python

**Comment by peter1017** [comment]
Thanks for prompt reply. I've followed your Youtube video step-by-step.
Attempted the output stage three times with no luck??

**Comment by matteocontrini** [comment]
Oh I wasn't aware of that video, it's not actually mine :)
Another of way of launching the script would be to browser in Windows Explorer to the folder where you have the `convert.py` file, then click in the "address bar" at the top of the windows and write `cmd`. Then, in the window that opens, type `python convert.py`.
If it doesn't work, post here the output of that window.

**Comment by peter1017** [comment]
Ah, sorry. Thought it was you!

Output file below.

[image: Inline images 1]

**Comment by matteocontrini** [comment]
Images don't get uploaded, post the output text, please.

**Comment by peter1017** [comment]
Thank you - below.


C:\SMS backup\smsBackup\sms-wp-to-android-master>convert.py
Total count of messages: 3570

[====================] processing 3570Traceback (most recent call last):
  File "C:\SMS backup\smsBackup\sms-wp-to-android-master\convert.py", line
90, i
n <module>
    with open(os.path.join(path, 'wp_messages.xml'), 'w', encoding='utf-8')
as f
ile:
TypeError: 'encoding' is an invalid keyword argument for this function

**Comment by matteocontrini** [comment]
Download the updated repository and try again. It should work!

**Comment by peter1017** [comment]
Perfect - thank you so much for your help.
