### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by helenatrial** [matteocontrini/sms-wp-to-android#29]
Hi! 

A newbie here so apologies if this is a silly question (googling didn't solve this).

I've created the backup file (.msg), and have it transferred on my computer's desktop (Mac 10.12.2). I downloaded python (2.7.13). I downloaded your program.

And now I'm stuck. I understood that you write "python convert.py" to the terminal, but I get this as a result:
can't open file 'convert.py': [Errno 2] No such file or directory

I'm not sure what I'm doing wrong, or maybe I just don't know what I'm doing (more likely). I ended up here via your blog and as you encouraged to raise an issue here for help, I'm reaching out! Appreciate any help you can give :)

**Comment by matteocontrini** [comment]
Hi, make sure you're launching the terminal in the folder where the `convert.py` file lies.
http://lifehacker.com/launch-an-os-x-terminal-window-from-a-specific-folder-1466745514

**Comment by helenatrial** [comment]
Thanks for the quick reply! I managed to do that, but the result was a few lines of errors. However, in your blog post comments "Madboy" had another suggestion, and that seems to have done the trick!

I have now my texts from my windows phone on my new android, so I can't thank you enough! 

Now the only task left is to figure out how to get the 6 months of backed up texts from onedrive that my wp refused to restore on my phone...aargh.
