### ISSUE TITLE
Synthax error while converting 58k SMS

### ISSUE THREAD

**Issue by noknok79** [matteocontrini/sms-wp-to-android#3]
please help, encountering error while converting a 58000+ SMS from my Lumia 920

C:\Python27>python convert.py
Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 75, column 3774

please help! thank you!

**Comment by matteocontrini** [comment]
Hi,
don't worry. I'll help you.
As you can read in the last line of the error output, there's something wrong at line 75, column 3774. It means there's a character that's been encoded in an invalid way, and it can't be parsed.
If you have Notepad++ or Sublime Text installed, open the xml file with the editor and scroll down to line 75. Then scroll horizontally untile you find the column number 3774. If you click in the middle of a line to put the caret, you'll have the column number shown in the status bar at the bottom.
If you want, you can also send me the file privately and I'll check.

Anyway, when you find that column, please copy here what you've found. There should be something like "\u84739" (numbers are random here) which could be invalid.
Let me know if you are able to get there.

Thanks.

**Comment by noknok79** [comment]
Sorry, but I tried to convert .msg to an .xml so I can restore it using SMS Backup and Restore for android. what XML you're referring to? :D sorry for my ignorant. :D

**Comment by matteocontrini** [comment]
Sorry, the msg file is an XML file inside, so just open that one :)

**Comment by noknok79** [comment]
SMAC&#x11;ALERT its an SMS alert

**Comment by noknok79** [comment]
is it possible to send you the whole .msg you convert it to .xml so I can easily restore it to my SMS Backup and restore, if you're not busy? :D

**Comment by noknok79** [comment]
> SMAC&#x11;ALERT

**Comment by noknok79** [comment]
its a special character that even this cant reco "SMAC&#x11;ALERT"

**Comment by noknok79** [comment]
"SMAC & # x 1 1 ; ALERT" w/ spaces

**Comment by noknok79** [comment]
its not that so important text, we can ommit/delete that so I can save other SMS. :D

**Comment by matteocontrini** [comment]
That's the issue, indeed :)
You can delete those symbols that start with `&` and end with `;`. Those characters could appear multiple times in the file, so you could use Find and Replace to remove them all.
If you prefer sending me the file, I'm available, my email address is on my GitHub profile. I'll respect your privacy.

**Comment by noknok79** [comment]
mail me sir to nokiev@yahoo.com I'll reply with attachment, so your email is kept. :D

**Comment by noknok79** [comment]
hold on, I'm just re-backup my sms for the latest. :D

**Comment by noknok79** [comment]
Sir, I just did it! its already done! thanks for the script! more power to you! thank you very much sir!

**Comment by matteocontrini** [comment]
Awesome ;)

**Comment by noknok79** [comment]
we should spread the good news to all Windows Phone Users who wishes to migrate to Android! :D clap clap clap!

**Comment by noknok79** [comment]
will you give me permission to spread the link How To? :D

**Comment by matteocontrini** [comment]
Of course :)
