### ISSUE TITLE
Can not convert, error when parse

### ISSUE THREAD

**Issue by danghung1202** [matteocontrini/sms-wp-to-android#30]
Hi @matteocontrini , first of all i would like to say thank you for your tool, however when i convert, there is an error as below
![image](https://cloud.githubusercontent.com/assets/13251426/22147424/1f7e5000-df3b-11e6-9a40-93dc9eae3c29.png)

This is file which i try to convert. 
https://drive.google.com/file/d/0B0Qw0rhsC0SRRGNWb2xsOFJZTUk/view

Regards

**Comment by matteocontrini** [comment]
Remove/replace any weird character at the specified line
