### ISSUE TITLE
syntaxerror: invalid syntax

### ISSUE THREAD

**Issue by kenshi1023** [matteocontrini/sms-wp-to-android#32]
Hi, how do i get this to work on windows 10?
And will this script work on .vmsg format for windows 10 phone sms backup?
I installed python 2.7 and 3.6, 2.7 i get the invalid syntax and on 3.6 unexpected...
Do you know what i did wrong? Thanks

![image](https://cloud.githubusercontent.com/assets/26100365/23440493/113bb834-fdd1-11e6-9aca-24fd47f17e7d.png)

![image](https://cloud.githubusercontent.com/assets/26100365/23440567/7828ee68-fdd1-11e6-928f-08ce167f6775.png)

**Comment by matteocontrini** [comment]
`cmd` => `python convert.py`
