### ISSUE TITLE
missing support for newline characters

### ISSUE THREAD

**Issue by adam-polyak** [matteocontrini/sms-wp-to-android#36]
Hi,

The newline characters are just handled as newline characters on WP platform and exported to .msg in this way as well.
On Android the newline characters are substituted by `&#10;` sequence, but the converter doesn't change them.
Could you please add this to improve the converter?

Thanks,
Adam

**Comment by matteocontrini** [comment]
Hi, thanks for reporting this. Do you have any (pseudo)official source that says that `&#10;` should be used for "newline"?

**Comment by adam-polyak** [comment]
Hi, unfortunately not, just figured it out based on my experinces when I did a conversion manually before. I used Android 5.0 with SMS Backup & Restore 9.73.119 (current version). Do you have a chance to try it out?

**Comment by matteocontrini** [comment]
I'll try later today

**Comment by matteocontrini** [comment]
It was a bug. Quite big, indeed. Thank you.

**Comment by adam-polyak** [comment]
Thansk for the quick respond and fix!
