### ISSUE TITLE
Unable to convert my .msg file file into .xml file?

### ISSUE THREAD

**Issue by Abdullah2050** [matteocontrini/sms-wp-to-android#37]
Hello,
I've read your blog and followed it as describe but I didn't resolve my issue. It shows some Praserror when script begins. I need to convert the attached (.msg file = 4.1 MB). It contains very important data. I need to convert it to .xml file so that I could recover it on android. I will be very thankful to you if you convert this file. 
FYI my source phone is Lumia 630 and Destination phone is Samsung Galaxy S7. Maybe this information is helpful in any case. Thanks again!!!
[backup+restore_Abdullah.zip](https://github.com/matteocontrini/sms-wp-to-android/files/888343/backup.restore_Abdullah.zip)

**Comment by matteocontrini** [comment]
Extract the zip and use the .msg file contained in the smsBackup directory

**Comment by Abdullah2050** [comment]
I already did that. It doesn't work :-(

**Comment by matteocontrini** [comment]
[wp_messages.zip](https://github.com/matteocontrini/sms-wp-to-android/files/888352/wp_messages.zip)

**Comment by Abdullah2050** [comment]
Well I really appreciate that but the file size is just 523 KB while the original file is 4.1 MB.
Would it contain the whole data. I'm a bit confused about it....

**Comment by matteocontrini** [comment]
It's a compressed archive, it's normal.

**Comment by Abdullah2050** [comment]
Oops that's my BAD...Sorry about that I'm not an IT Guy. Thank you soooooo Much for HELP!!!!

**Comment by Abdullah2050** [comment]
THANK U THANK U SOOOOO MUCH :-D
