### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by sebastian-frysztak** [matteocontrini/sms-wp-to-android#39]
Is it really necessary? Would you be okay with me stripping it down and adding proper CLI?

**Comment by matteocontrini** [comment]
I think it is. The script is meant for anyone wanting an easy way to convert messages. And still, I get emails of people having issues with running the Python script. Removing the GUI would be a disaster for them, I guess 😅

**Comment by sebastian-frysztak** [comment]
I see. What about CLI? I could add it as an option and leave GUI untouched.

**Comment by matteocontrini** [comment]
Of course, that would be fine

**Comment by macmusicman** [comment]
Hi. Firstly, great app! The issue I noticed is that the Android "SMS Back and Restore" app appears to be looking for a file with a prefix of "sms-*.xml" in the filename. It didn't see the generated wp-messages.xml file until I prefixed it with "sms-". This tip may help others. Can you confirm I'm right, and if so, I'll try and create a pull request.
