### ISSUE TITLE
Missing some SmS?

### ISSUE THREAD

**Issue by noknok79** [matteocontrini/sms-wp-to-android#4]
good day sir!

your python script was greatful, but I just notice with my 58k SMS, I noticed that messages are only restored dated 10-25-2015 but when I view the xml file, on SMS Backup & Restore View, I have SMS dated 2011 below

but during restoring using SMS Backup & Restore, the oldest is SMS dated 10-25-2015.

can you assist me again with this?

thanks in advance!

**Comment by matteocontrini** [comment]
Can you explain better? Is the xml file correct, just that the viewer doesn't display them? After you've imported them, do you see them all in your Android messaging app?

**Comment by noknok79** [comment]
ok the converted wp_xml file from the out of your python script from .msg wp sms is good, when I tried to restore it using SMS Backup & Restore android apps, there's a button view there, which it will view the content SMS from the XML files.

but during restoring process, after it restored with some 10 errors, the SMS messages only restored was dated 10-23-2015 only. there's a nearly 4yrs SMS is not successful restored.

**Comment by matteocontrini** [comment]
Are you sure it's not because of conversations, so that the date makes you think it's the oldest one? Anyway, I suggest that you contact the app developer, since I don't know how that feature works exactly.

**Comment by noknok79** [comment]
ah ok, is there any similar apps can be use for your xml files converted from WP SMS? :D

**Comment by matteocontrini** [comment]
Not sure about that. There could be other apps but I don't which format they accept.
