### ISSUE TITLE
Restore messages

### ISSUE THREAD

**Issue by 74AJ** [matteocontrini/sms-wp-to-android#40]
Having issues restoring messages when I already have messages on my phone. Seems like you cannot merge threads (e.g. message thread both in backup and phone doesn't merge) or restore messages with date before the first message that existed on the phone before restoring. 

Don't know if that is a limitation of the generated xml file or of it is the sms backup restore app. When backing up the messages using the app the number of sms indicates that messages exists on the phone but are not visible. Threads with messages older than the first message that existed on the phone before import are not possible to open - you just get sent back to the list of threads.

Have you tried this?

**Comment by matteocontrini** [comment]
This would be an issue with the Backup & Restore app, it has nothing to do with the conversion script.

**Comment by 74AJ** [comment]
You may have closed this prematurely.

When I tried to make a backup from the backup/restore tool you recommend the messages that fail to open (you tap on the thread but it does not open) and then view the backup from said tool, the messages are displayed as MMS, not SMS and I know for sure that the messages were not MMS messages at all at any point in time.

This leads me to believe that something funky happened when running the script on the original backup from the WP.

Let me know if you need additional details.

Thank you,
Anders

**Comment by matteocontrini** [comment]
Could you take a look inside the xml file generated by the script of this repo and see if there are mms tags (just search for `<mms`)?

**Comment by 74AJ** [comment]
Hi,
Thank you for the reply!

Yes there are very many instances of mms tags.

Anders

**Comment by matteocontrini** [comment]
@sschuberth can you take a look at this issue? It seems that MMS support broke something

**Comment by sschuberth** [comment]
I've proposed a PR. Sorry for the regression! Please give it a try, @74AJ.

**Comment by matteocontrini** [comment]
@74AJ I'm not sure if you're a developer or if you have experience with git/GitHub, so... in case you don't, you should [go here](https://github.com/sschuberth/sms-wp-to-android/tree/fix-mms-vs-sms) and clone the repo (or download the ZIP) again. If you're able to try the whole process again and reimport the messages on your phone, let us know how it goes.

**Comment by 74AJ** [comment]
I'll give it a try tomorrow morning and let you know.

Anders


________________________________

**Comment by 74AJ** [comment]
HI,
I am not a developer per se but I do have some experience…

Anyways, this worked much better! Messages import although I did observe some garbage characters as interprets line feed incorrectly and instead displays “&#10;” (if it disappears in translation, that is the following characters as a string:

& Ampersand
# Hash
10
; Semicolon

Thank you,
Anders

**Comment by matteocontrini** [comment]
That shouldn't actually happen. `&#10;` is just the XML way for saying "new line", and it should be correctly parsed when importing. It was introduced with #43 (issue #41). Previously new lines were just ignored. I'll track this problem in another issue
