### ISSUE TITLE
Only newline characters are XML-fied, not quotations

### ISSUE THREAD

**Issue by euler314** [matteocontrini/sms-wp-to-android#41]
To replace all characters by XML characters, [line 57](https://github.com/matteocontrini/sms-wp-to-android/blob/master/convert.py#L57) should be replaced by

    body = body.replace("\n", "&#10;")

Moreover, it would be a good idea to do a replacement for *all* possible XML characters (perhaps there is a readymade function available that can be used) to handle ampersands etc. in SMS messages. Otherwise, a naive method would be to do say (on line 57):

    body = text.replace("\"", "&quot;")
    body = body.replace("\n", "&#10;")
    body = body.replace("&", "&amp;")

**Comment by matteocontrini** [comment]
You're right. A PR would be appreciated.
