### ISSUE TITLE
Unclosed Token

### ISSUE THREAD

**Issue by Skyzeun** [matteocontrini/sms-wp-to-android#48]
Hey,

I've had this error and i don't know how to correct this :/

![image](https://user-images.githubusercontent.com/25200991/29112094-028480c8-7ced-11e7-9c5a-9cf450b27f4f.png)

I search on issue but nobody have this problem.

Can you help me plz? :/

**Comment by matteocontrini** [comment]
It seems there's an error in the XML file, specifically at line 311, column 177. You'll need to check what's going on there, but you should have some experience with the structure of XML files

**Comment by Skyzeun** [comment]
Thanks for the answer.

The problem it's it doesn't create XML files on my desktop so i can't check in the file. I've tried to check in .MSG but nothing :/

**Comment by matteocontrini** [comment]
The .msg file is the XML file I was referring to

**Comment by Skyzeun** [comment]
ah ok sorry ^^
i try to fix this and i back to you if i have a problem.

**Comment by Skyzeun** [comment]
Ok it's good just need to add at the end after "</Message>" this "</ArrayOfMessage>"

Thx for help :D

**Comment by matteocontrini** [comment]
:)
