### ISSUE TITLE
Can't backup MMS

### ISSUE THREAD

**Issue by RenanK** [matteocontrini/sms-wp-to-android#5]
The Windows app makes a separate file for MMS, which makes your script close itself as soon as I open it.

**Comment by matteocontrini** [comment]
Which file does it create? I have never used MMS so I have no idea of how it works with the backup...

**Comment by ap287** [comment]
How would I modify this script so that it reformats the WP MMS file to something Android-compatible? I have no programming experience, but if it's mostly a question of modification, and someone can provide some guidance, this could very well be my first foray into learning programming....

**Comment by matteocontrini** [comment]
You'd have to look at the XML file generated by Windows Phone, try to understand how media files are included/attached to the file and then make sure that the Python script is able to parse the MMS nodes (if any?) and convert them to the Android standard.

**Comment by MortenAgner** [comment]
I have just had the same experience as RenanK: The Windows app creates a quite large backup file, which means it must contain photos as well. But when this file is run through the script the output file (xml-file) isn't near as large. And when this file is used for a backup in the Android app only text appears. No photos.
I'm curious to learn what you programming guys find out.
Other than that I find the tool quite useful :+1:

**Comment by sschuberth** [comment]
Is there a spec how the XML format for MMS supported by SMS Backup & Restore is supposed to look like? If so, I could probably give it a try to add that functionality.

**Comment by sschuberth** [comment]
The adventurous in this thread may want to try [convert.py](https://github.com/sschuberth/sms-wp-to-android/blob/mms/convert.py) from my *mms* branch. I'll file a PR once I've tested it a bit myself. Right now the code is completely untested.

**Comment by sschuberth** [comment]
Ok, I've tested the import myself now (export from Lumia 1020, import into Nexus 5), fixed a few issues, and believe to be good for PR now.

**Comment by matteocontrini** [comment]
Thank you @sschuberth! I'd wait for someone else to try your work before merging.

**Comment by sschuberth** [comment]
Sure thing. BTW, you can easily try it out yourself (if you still have a Windows Phone) by sending yourself an MMS before doing the export.
