### ISSUE TITLE
how to sms-android-to-wp

### ISSUE THREAD

**Issue by clachapelle** [matteocontrini/sms-wp-to-android#52]
Just bought an Alcatel Idol 4S Windows 10, and could not get the Switch to Windows Phone application work, and since Microsoft seem to no longer support this application, and can't find any other easy way to export all my android sms (Asus Zenfone 3).

I already exported all the sms from my android using Wondershare MobileGo SMS export, but the file is using a different xml format than the Microsoft Contacts+Messages Backup application, so I can't restore the file as is.

Can your code could be used to do the conversion FROM Android, TO Windows Phone?

Thanks.

**Comment by matteocontrini** [comment]
Hi, no, this script is for converting the XML file from WP to Android
