### ISSUE TITLE
No encoding declared

### ISSUE THREAD

**Issue by joanzen** [matteocontrini/sms-wp-to-android#53]
I used convert.py successfully on one of my Windows Phones; it worked perfectly.  However, when I exported the SMS of my second phone and tried converting that one, I received the following error.  

![convertdotpy error](https://user-images.githubusercontent.com/34200955/33521713-be314d32-d7a7-11e7-82ee-868e6ea8d93c.PNG)

Any help would be appreciated.  

Thanks!

**Comment by joanzen** [comment]
My apologies folks.  As I'm sure you saw immediately, I messed up in my execution by not actually calling convert.py this time.  Embarrassing...

**Comment by matteocontrini** [comment]
Sorry for not replying earlier, I read the email but forgot to answer. Glad you solved, that was the issue indeed.

**Comment by joanzen** [comment]
Matteo,

Thanks very much for responding, but I apologize for wasting your time with my stupid mistake.  The program worked perfectly when I actually executed it!  😊

Thanks,
Kevin


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
