### ISSUE TITLE
Help me convert them!

### ISSUE THREAD

**Issue by sontungduog** [matteocontrini/sms-wp-to-android#56]
Your code isn't working for me! I try many times in both windows and Ubuntu. I uploaded my msg file in attachment, please kindly help me convert them to XML file. Thank you and God bless you!

remove ".helpme.txt"
[Fri, Aug 10 2018, 21-50-08 PM.msg.helpme.txt](https://github.com/matteocontrini/sms-wp-to-android/files/2285464/Fri.Aug.10.2018.21-50-08.PM.msg.helpme.txt)

**Comment by matteocontrini** [comment]
Hi, here is the converted file.

[sms-wp.zip](https://github.com/matteocontrini/sms-wp-to-android/files/2286347/sms-wp.zip)

**Comment by sontungduog** [comment]
You are amazing. Thank you so so much!!
