### ISSUE TITLE
Cannot find xml file

### ISSUE THREAD

**Issue by FardawsHassan** [matteocontrini/sms-wp-to-android#57]
with python 2.7 I opened convert.py and selected the msg file....when i processed that file i couldnot find any xml file....I searched in whole computer for "wp_messages.xml" name file but there wasn't any....the msg file was at the same folder where convert.py was.....

can you please convert it for me ? it will be very helpfull....thanks
[wp_messages.zip](https://github.com/matteocontrini/sms-wp-to-android/files/2286292/wp_messages.zip)

**Comment by matteocontrini** [comment]
Here is the converted file.

[sms-wp.zip](https://github.com/matteocontrini/sms-wp-to-android/files/2286353/sms-wp.zip)

**Comment by FardawsHassan** [comment]
Thank u so much 😊
All msg has been restored.
