### ISSUE TITLE
Messages Appear In Reverse Order

### ISSUE THREAD

**Issue by Ginger-Jim** [matteocontrini/sms-wp-to-android#6]
After doing the SMS restore, my messages appeared in reverse order. So when you click on a conversation thread, the most recent message is at the top. 

Is there a way to get the most recent message to appear at the bottom of the thread, ie just above the text input box?

(Running Android 5.1.1)

**Comment by matteocontrini** [comment]
They should be in chronological order if timestamps were successfully imported. Can you check that?

**Comment by Ginger-Jim** [comment]
Timestamps show that they are chronologically ordered, but with newest messages at the top and oldest message at the bottom.

It should be the other way round.
