### ISSUE TITLE
Command does nothing

### ISSUE THREAD

**Issue by MikeyTsi** [matteocontrini/sms-wp-to-android#61]
This is probably related to me not knowing much about Python, but when I try to run the convert it's not giving any output or converting the file.

I installed python 2.7.16, I've got the convert.py files in c:\python27\scripts\sms-wp-to-android-master.  The msg file I want to convert is there as well.

Here's what I see for output:

c:\Python27\Scripts\sms-wp-to-android-master>python convert.py

c:\Python27\Scripts\sms-wp-to-android-master>

**Comment by matteocontrini** [comment]
Does it ask to select a file when you run "python convert.py"? It should show a file picker

**Comment by MikeyTsi** [comment]
Nope, what's above is the entirety of the output I get.

**Comment by MikeyTsi** [comment]
Ah.  Didn't need to specify "python", I just did "convert.py" and I got the prompt and it appears to have converted the file.

**Comment by matteocontrini** [comment]
Glad you made it, I wouldn't have thought about that :)
