### ISSUE TITLE
Throws and error upon running the .py file

### ISSUE THREAD

**Issue by Mike-88-Alex** [matteocontrini/sms-wp-to-android#62]
Hi, I downloaded the zip and extracted it and put my .msg file in there as well. I tried to run the python file through cmd and with VS Code and it gives an error
![error](https://user-images.githubusercontent.com/56084050/174318052-7b507a1d-87e3-4606-87de-22d0fcbc4940.png)
:

**Comment by matteocontrini** [comment]
Hi, as long as you don't have MMS to convert, try removing line 3 from the `convert.py` file and it should work.

**Comment by Mike-88-Alex** [comment]
Thanks, it worked. I suppose the original version was made to convert MMS's also along with SMS's ?

**Comment by matteocontrini** [comment]
Yes, but it makes use of a Python feature that is not available anymore so it doesn't run.

Glad it helped.
