### ISSUE TITLE
Error during conversion

### ISSUE THREAD

**Issue by JohnLandon** [matteocontrini/sms-wp-to-android#7]
Hi Matteo,

I ran the script just fine on one phone, but on the second, I'm getting this error:
C:\Python27>python convert.py
Total count of messages: 16479

[=================== ] processing 16468Traceback (most recent call last):
  File "convert.py", line 50, in <module>
    address = list(m.find('Recepients'))[0].text
IndexError: list index out of range

Any ideas?

**Comment by JohnLandon** [comment]
Looks my original paste of error missed a part.  Here's the actual:

C:\Python27>python convert.py
Total count of messages: 16479

[=================== ] processing 16468Traceback (most recent call last):
  File "convert.py", line 50, in <module>
    address = list(m.find('Recepients'))[0].text
IndexError: list index out of range

**Comment by JohnLandon** [comment]
For some reason it's leaving out the "<module>" after line 50, in

**Comment by JohnLandon** [comment]
"module"

**Comment by matteocontrini** [comment]
Hi,
it means that there's probably a message without a recipient, which is strange. Are you able to find taht message in the file?
Or if you can, send me the file and I'll try to fix this.

Let me know

**Comment by Peter11111** [comment]
Hi,

I am getting the errors shown in the attached file.

Can you help?
![error](https://cloud.githubusercontent.com/assets/18420485/14460610/c4c93d18-0101-11e6-82e5-f7c567c6c7e6.JPG)


Thanks.

**Comment by matteocontrini** [comment]
Can you perhaps what's in the file at line 146, column 1523? You can do that in an editor like Notepad++ or Sublime Text or similar.

**Comment by minedeljkovic** [comment]
I had the sam issue as @Peter11111 . Problem was that source msg file had some strange character (&#x11;) encoded in given position (given by xml.etree.ElementTree.ParseError description). Replaced all occurrences of that character and it solved this issue.

**Comment by matteocontrini** [comment]
You're right, I've had other reports of the same issue with that entity!
