### ISSUE TITLE
problem with instructions for transfer

### ISSUE THREAD

**Issue by mapalmer13** [matteocontrini/sms-wp-to-android#9]
Hi.  I am in desperate need of your assistance.  I am trying to transfer my contacts, texts and pictures from my Lumia 925 to my new LG G4.  I am not very good with technology, and your instructions seemed very straight forward.  I did not have any problem backing up the phone, without a sim card, to the documents folder on the phone.  The backup showed complete.  I downloaded Python from your link.  I tried to download the documents folder on my phone to my laptop using a USB cable.  The folder cannot be found.  I tried to upload from the phone to the Outlook cloud without success.  Again, no folder.  Now I cannot even change the backup location from the phone documents to any other location.  Any help you can offer is greatly appreciated.  Thank you!

**Comment by matteocontrini** [comment]
Hi, what do you mean with "the folder cannot be found" exactly?

**Comment by mapalmer13** [comment]
Hi Mr. Contrini,
Thank you so much for contacting me. I cannot find the folder...it is the
documents folder on the Lumia that I backed up the phone to...when I
connect the phone to the computer.

**Comment by matteocontrini** [comment]
Are you using Windows on desktop? When you connect your phone to the computer and you go to Computer --> Lumia 925 --> Internal storage, isn't the "Documents" folder there?

**Comment by mapalmer13** [comment]
Hi Mr. Contrini,  I am using Windows 10 on my laptop.  When I connect the
Lumia, the documents folder is empty.  I apologize for the delay in
responding.  My son paid me a surprise over night visit and I was not able
to check my email.  Thank you again for your time and help.  Mary Anne

**Comment by matteocontrini** [comment]
Do you have Windows Phone 8.1 on your Lumia? What happens when you try changing the output folder in contacts+message backup?

**Comment by mapalmer13** [comment]
I will try to provide you with all of the settings that may be relevant.  I
have a Windows Phone 8.1 Lumia.
Wi-Fi -  on my home network
airplane mode - off
bluetooth - off
NFC - on
internet sharing - off
backup - save to the cloud
contacts +message backup- backup contacts and messages to SD card with
current backup location phone\documents\smsbackup

I was able to backup contacts, sms and mms messages to the phone, but I do
not know what to do from there to find the "generated file".

I have opened OneDrive on my laptop (running Windows 10), plugged in the
Lumia, and even attempted to back up the phone to OneDrive, but cannot even
do this.  I have been able to do this in the past, but I am guessing that
because my contacts + message backup has been changed to SD card, it may be
preventing me from doing so now.  I have tried to change the setting from
SD card, but cannot.  It just asks me to pick a folder when i press the 3
dots in the bottom right of the screen that I used to select the folder
when I started trying to make to follow the instructions.

I am so very sorry for all of this.  Again,  your time and assistance is
greatly appreciated.

**Comment by matteocontrini** [comment]
When it asks to pick a folder, are you able to choose a folder that you can find then later from your computer?

**Comment by mapalmer13** [comment]
I chose the documents folder because I thought that would be easiest to
find.  Where on the phone would I finds that there are actually contents in
the documents folder? How do I get that folder to my computer?  I do not
receive an option to import documents or folders from my phone to my
computer as I do when pictures are imported/transferred.  I know this is my
fault and my ignorance of technology has caused all of this.  I need to
keep these texts for legal purposes and the phone is not working well
enough (third warranty replacement) to keep it alive much longer.  Your
patience is appreciated as much as your help.

**Comment by matteocontrini** [comment]
You could also download this official file manager app

https://www.microsoft.com/en-us/store/apps/files/9wzdncrfj3pl

And try finding the backup in documents. Then you can press "share" and send it to your computer via email or something else.

**Comment by mapalmer13** [comment]
Ok.  I will download that app.  I would look where for the backup in
documents...the phone or the computer?

**Comment by matteocontrini** [comment]
You download and launch that app, then you browser to "Phone storage", "Documents" and you should find something there if you already backed up something earlier. Then you select the files that you find and send them to the computer.

**Comment by mapalmer13** [comment]
Thank you so much.  I will give it a try!

**Comment by mapalmer13** [comment]
Hi Mr. Contrini.  I am still unable to correct my problem.  I am sorry for
the delay in contacting you.  I have not been home.  Any other suggestions
would be truly appreciated.  Thank you.

**Comment by matteocontrini** [comment]
What's the problem now?

**Comment by mapalmer13** [comment]
Same issue.  I have downloaded the apps you suggested.  All it succeeded in
doing was tripling all my texts instead of saving them to any file or
folder.  I cannot even change the "contact +message backup" from sd card to
whatever the original used to be.  So sorry

**Comment by matteocontrini** [comment]
Sorry but I can't help as your responses are unfortunately too confusing to understand the real issue...
